### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dtolnay** [TimSimmons/failure_test#1]
```rust
fn point_to_json(point: Point) -> Result<String, failure::Error> {
    serde_json::to_string(&point)?
}
```

The return type of [`serde_json::to_string`](https://docs.serde.rs/serde_json/fn.to_string.html) is `Result<String, serde_json::Error>`.

So after applying [`?`](https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html) which goes from `Result<T, _>` to `T`, the type of the expression `serde_json::to_string(&point)?` is `String`.

---

```console
  --> src/main.rs:40:5
   |
40 |     serde_json::to_string(&point)?
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |     |
   |     expected enum `std::result::Result`, found struct `std::string::String`
   |
   = note: expected type `std::result::Result<std::string::String, failure::Error>`
              found type `std::string::String`
```

This message tells you that the type of `serde_json::to_string(&point)?` is `String` (which it is).

Also it tells you that `String` is different from `Result<String, failure::Error>`, which is what `point_to_json` declares that it returns.

The function does not compile because the type being returned, `String`, is different from the type that was supposed to be returned by `point_to_json`, `Result<String, failure::Error>`.

@TimSimmons

**Comment by TimSimmons** [comment]
YES, that makes much more sense. I should have read this better:
```
The ? placed after a Result value is defined to work in almost the same way as the match expressions we defined to handle the Result values in Listing 9-6. If the value of the Result is an Ok, the value inside the Ok will get returned from this expression, and the program will continue. If the value is an Err, the value inside the Err will be returned from the whole function as if we had used the return keyword so the error value gets propagated to the calling code.

There is a difference between what the match expression from Listing 9-6 and the ? operator do: error values used with ? go through the from function, defined in the From trait in the standard library, which is used to convert errors from one type into another. When the ? operator calls the from function, the error type received is converted into the error type defined in the return type of the current function. This is useful when a function returns one error type to represent all the ways a function might fail, even if parts might fail for many different reasons. As long as each error type implements the from function to define how to convert itself to the returned error type, the ? operator takes care of the conversion automatically.
```

I was able to make it do what I expected:
https://github.com/TimSimmons/failure_test/commit/edc8acd844578934739c10042fc1687ba6180d1c

Thank you so so so much for your time, I really seriously appreciate it, you didn't have to take the time to help me :heart: :heart: :heart:
